version: '3'

services:

  the-form-postgres:
    image: postgres
    container_name: the-form-postgres
    restart: always
    tty: true
    env_file:
      - .env.postgres
      - .env.postgres.local
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/home/postgres
      - ./data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - node-network

  the-form-server:
    image: mbaluev/the-form-server:latest
    platform: linux/x86_64
    container_name: the-form-server
    env_file:
      - .env.server
      - .env.server.local
    networks:
      - node-network
    ports:
      - "8081:8081"
    volumes:
      - ./files:/home/files

  the-form-client:
    image: mbaluev/the-form-client:feature-v2
    platform: linux/x86_64
    container_name: the-form-client
    networks:
      - node-network
    ports:
      - "3000:3000"

  the-form-nginx:
    build:
      context: nginx
    container_name: the-form-nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - the-form-client
      - the-form-server
      - the-form-postgres

networks:
  node-network:
    driver: bridge