version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    tty: true
    env_file:
      - .env.postgres.local
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/home/postgres
      - ./data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - node-network

  server:
    image: mbaluev/the-form-server:latest
    platform: linux/x86_64
    container_name: server
    networks:
      - node-network
    ports:
      - "8081:8081"
    volumes:
      - ./files:/home/files

  client:
    image: mbaluev/the-form-client:latest
    platform: linux/x86_64
    container_name: client
    networks:
      - node-network
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - client
      - server
      - postgres

networks:
  node-network:
    driver: bridge